### ISSUE TITLE
the aws-cdk-lib/aws-amplify class only has L1 cfn constructs. This L2 Example is not valid

### ISSUE THREAD

**Issue by vaughngit** [nikovirtala/cdk-amplify-console#18]

**Comment by nikovirtala** [comment]
It was when this code was last changed ... two years ago 😅 At that time, AWS CDK was in version `2.0.0`, and the `experimental` constructs had not been moved to separate `alpha` packages.

I will fix my implementation soon-ish.

**Comment by nikovirtala** [comment]
Fixed on https://github.com/nikovirtala/cdk-amplify-console/commit/5389e1f7e4f82f476a490a4648a85ce742573137
